"""bot: conversation state and processed messages

Revision ID: 042672a46330
Revises: 41f1896507a4
Create Date: 2026-08-18 09:45:22.632009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042672a46330'
down_revision = '41f1896507a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_processed_messages',
    sa.Column('message_id', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('bot_conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('flow', sa.String(length=50), nullable=True),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bot_conversation_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bot_conversation_states_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_conversation_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bot_conversation_states_user_id'))

    op.drop_table('bot_conversation_states')
    op.drop_table('bot_processed_messages')
    # ### end Alembic commands ###
