"""add category_suggestion_patterns table

Revision ID: 28f3c6aa9fc2
Revises: 0c2ca9e0ce29
Create Date: 2026-09-01 21:17:40.189152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f3c6aa9fc2'
down_revision = '0c2ca9e0ce29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_suggestion_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('normalized_description', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'normalized_description', 'category_id', name='uq_category_suggestion_user_description_category')
    )
    with op.batch_alter_table('category_suggestion_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_suggestion_patterns_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_suggestion_patterns_normalized_description'), ['normalized_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_suggestion_patterns_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_suggestion_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_suggestion_patterns_user_id'))
        batch_op.drop_index(batch_op.f('ix_category_suggestion_patterns_normalized_description'))
        batch_op.drop_index(batch_op.f('ix_category_suggestion_patterns_category_id'))

    op.drop_table('category_suggestion_patterns')
    # ### end Alembic commands ###
