"""add bank_name to credit_cards

Revision ID: 41f1896507a4
Revises: 724844dd235a
Create Date: 2026-07-24 19:09:53.486667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f1896507a4'
down_revision = '724844dd235a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_column('bank_name')

    # ### end Alembic commands ###
