"""phase 3: transfers between accounts

Revision ID: af34afe8e211
Revises: c983b1a4d985
Create Date: 2026-07-24 12:32:05.581431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af34afe8e211'
down_revision = 'c983b1a4d985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=False),
    sa.Column('to_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_transfer_amount_positive'),
    sa.CheckConstraint('from_account_id <> to_account_id', name='ck_transfer_distinct_accounts'),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_from_account_id'), ['from_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_account_id'), ['to_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_user_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_to_account_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_account_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_date'))

    op.drop_table('transfers')
    # ### end Alembic commands ###
