"""phase 2: credit cards and invoices

Revision ID: c983b1a4d985
Revises: 3f2e9340634a
Create Date: 2026-07-24 12:16:36.074674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c983b1a4d985'
down_revision = '3f2e9340634a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_day', sa.SmallInteger(), nullable=False),
    sa.Column('due_day', sa.SmallInteger(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('closing_day BETWEEN 1 AND 31', name='ck_credit_card_closing_day'),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name='ck_credit_card_due_day'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_cards_user_id'), ['user_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=False),
    sa.Column('reference_month', sa.Date(), nullable=False),
    sa.Column('closing_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credit_card_id', 'reference_month', name='uq_invoice_card_reference_month')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_credit_card_id'), ['credit_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_card_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_credit_card_id'), ['credit_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_transactions_credit_card_id_credit_cards', 'credit_cards', ['credit_card_id'], ['id']
        )
        batch_op.create_foreign_key(
            'fk_transactions_invoice_id_invoices', 'invoices', ['invoice_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_invoice_id_invoices', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_credit_card_id_credit_cards', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_credit_card_id'))
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('credit_card_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_user_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_credit_card_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_cards_user_id'))

    op.drop_table('credit_cards')
    # ### end Alembic commands ###
