"""phase 4: recurring transactions

Revision ID: d1f0ffbefcf9
Revises: af34afe8e211
Create Date: 2026-07-24 12:40:40.973110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f0ffbefcf9'
down_revision = 'af34afe8e211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_generated', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_recurring_transaction_amount_positive'),
    sa.CheckConstraint('day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31', name='ck_recurring_transaction_day_of_month'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_recurring_id'), ['recurring_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_transactions_recurring_id_recurring_transactions',
            'recurring_transactions',
            ['recurring_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_transactions_recurring_id_recurring_transactions', type_='foreignkey'
        )
        batch_op.drop_index(batch_op.f('ix_transactions_recurring_id'))
        batch_op.drop_column('recurring_id')

    with op.batch_alter_table('recurring_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_transactions_user_id'))

    op.drop_table('recurring_transactions')
    # ### end Alembic commands ###
